on:
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn
      - run: yarn test
